name: auto-release
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    uses: alpine-ros/alpine-ros-ci-workflows/.github/workflows/auto-release.yaml@main
    secrets:
      token: ${{ secrets.AR_GITHUB_TOKEN }}
