name: release
on:
  issues:
    types: [opened, reopened, edited]

jobs:
  release-candidate:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Release ')
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: create release
        id: create_release
        uses: at-wat/catkin-release-action@v1
        with:
          issue_title: ${{ github.event.issue.title }}
          git_user: alpine-ros-bot
          git_email: 214657941+alpine-ros-bot@users.noreply.github.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: open pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.AR_GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head ${{ steps.create_release.outputs.created_branch }} \
            --title "Release "${{ steps.create_release.outputs.version }} \
            --assignee ${{ github.actor }}
