name: ci
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  issues: write
  pull-requests: write

jobs:
  test:
    uses: alpine-ros/alpine-ros-test-workflow/.github/workflows/ros1.yaml@main
    with:
      enable-bot-comment: true
    secrets:
      bot-comment-token: ${{ secrets.GITHUB_TOKEN }}
